stats:
  server:
    url: http://localhost:9090

server:
  port: 8080

spring:
  main:
    banner-mode: off

  sql:
    init:
      mode: always

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6542/main
    username: main
    password: main

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: true
    show-sql: true

application:
  name: main-service

logging:
  level:
    org.springframework.transaction.interceptor: TRACE
    org.springframework.web: INFO